# Generated by Django 4.2 on 2026-05-31 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('teacher', 'Преподаватель')], default='teacher', max_length=20, verbose_name='Роль')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фото профиля')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Пароль изменён')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('student', 'Студент'), ('employee', 'Сотрудник'), ('parent', 'Опекун')], max_length=20, verbose_name='Тип владельца')),
                ('owner_id', models.IntegerField(verbose_name='ID владельца')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('doc_type', models.CharField(blank=True, choices=[('passport', 'Паспорт'), ('snils', 'СНИЛС'), ('policy', 'Полис ОМС'), ('certificate', 'Аттестат'), ('order', 'Приказ'), ('other', 'Прочее')], default='', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('login', models.CharField(blank=True, default='', max_length=150, verbose_name='Логин')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('purpose', models.CharField(choices=[('register', 'Регистрация'), ('recover', 'Восстановление пароля'), ('delete_org', 'Удаление организации'), ('change_email', 'Смена email'), ('delete_account', 'Удаление аккаунта')], max_length=20, verbose_name='Цель')),
                ('payload', models.TextField(blank=True, default='', verbose_name='Данные (JSON)')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('attempts', models.IntegerField(default=0, verbose_name='Неверных попыток')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email-код',
                'verbose_name_plural': 'Email-коды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Отмечено')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращение (аббревиатура)')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Отмечено')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='Страница')),
                ('selector', models.TextField(verbose_name='CSS-селектор')),
                ('element_preview', models.CharField(blank=True, max_length=200, verbose_name='Превью элемента')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Комментарий к интерфейсу',
                'verbose_name_plural': 'Комментарии к интерфейсу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField(default=1, verbose_name='Номер группы')),
                ('year', models.IntegerField(verbose_name='Год начала')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.faculty', verbose_name='Факультет')),
                ('headteacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_groups', to='core.employee', verbose_name='Классный руководитель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['faculty', 'group_number'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('name', models.CharField(max_length=1000, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='institutions/', verbose_name='Фото')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Дата основания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в систему')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
                'ordering': ['name'],
                'unique_together': {('owner', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parents/', verbose_name='Фото')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.institution', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Опекун',
                'verbose_name_plural': 'Опекуны',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Фото')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.faculty', verbose_name='Факультет')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.group', verbose_name='Группа')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.institution', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.institution', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('question', models.TextField(max_length=2000, verbose_name='Вопрос')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_notes', to='core.institution', verbose_name='Учебное заведение')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
            ],
            options={
                'verbose_name': 'Вопрос по записи',
                'verbose_name_plural': 'Вопросы по записям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('role_type', models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('none', 'Без доступа')], default='teacher', max_length=20, verbose_name='Тип роли')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.institution', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
                'unique_together': {('institution', 'name')},
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='taught_subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.subject', verbose_name='Ведёт предметы'),
        ),
        migrations.CreateModel(
            name='DeleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('Faculty', 'Факультет'), ('Group', 'Группа'), ('Position', 'Должность'), ('Student', 'Студент'), ('Employee', 'Сотрудник'), ('Parent', 'Опекун')], max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Заявка на удаление',
                'verbose_name_plural': 'Заявки на удаление',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создал'), ('updated', 'Изменил'), ('deleted', 'Удалил')], max_length=20, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('old_data', models.TextField(blank=True, verbose_name='До изменения (JSON)')),
                ('new_data', models.TextField(blank=True, verbose_name='После изменения (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.institution', verbose_name='Учебное заведение')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_institutions',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='core.institution', verbose_name='Доступные организации'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='core.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун')], max_length=20, verbose_name='Тип связи')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parents', to='core.parent', verbose_name='Опекун')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parents', to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Связь студент-опекун',
                'verbose_name_plural': 'Связи студент-опекун',
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='GroupSubjectEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='core.employee', verbose_name='Преподаватель')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='core.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='core.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет в группе',
                'verbose_name_plural': 'Предметы в группах',
                'unique_together': {('group', 'subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('institution', 'short_name'), ('institution', 'full_name')},
        ),
    ]
