# Generated by Django 4.2 on 2026-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=500, verbose_name='Страница')),
                ('selector', models.TextField(verbose_name='CSS-селектор')),
                ('element_preview', models.CharField(blank=True, max_length=200, verbose_name='Превью элемента')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Комментарий к интерфейсу',
                'verbose_name_plural': 'Комментарии к интерфейсу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending_review', 'На рассмотрении'), ('pending_enrollment', 'На зачисление'), ('enrolled', 'Зачислен'), ('pending_expulsion', 'На отчисление'), ('expelled', 'Отчислен'), ('transferred', 'Переведён')], default='pending_review', max_length=30, verbose_name='Статус'),
        ),
    ]
