# Generated by Django 4.2 on 2026-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='object_type',
            field=models.CharField(choices=[('Faculty', 'Факультет'), ('Group', 'Группа'), ('Position', 'Должность'), ('Student', 'Студент'), ('Employee', 'Сотрудник'), ('Parent', 'Опекун'), ('Subject', 'Предмет')], max_length=50, verbose_name='Тип объекта'),
        ),
    ]
