# Generated by Django 4.2 on 2026-05-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_deleterequest_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отозвана')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
