# Generated by Django 4.2 on 2026-04-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_name_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='seed_phrase_hash',
            field=models.CharField(blank=True, max_length=256, verbose_name='Хэш сид-фразы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_owner', 'Владелец платформы'), ('superadmin', 'Суперадминистратор'), ('admin', 'Администратор'), ('teacher', 'Преподаватель')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='employee',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='parent',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='position',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='subject',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.institution', verbose_name='Учебное заведение'),
        ),
    ]
