# Generated by Django 4.2 on 2026-04-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_institution_user_display_name_user_seed_phrase_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seed_phrase_hash',
        ),
    ]
