# Generated by Django 4.2 on 2026-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_seed_phrase_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадминистратор'), ('admin', 'Администратор'), ('teacher', 'Преподаватель')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
    ]
