# Generated by Django 4.2 on 2026-05-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='is_teacher',
        ),
    ]
