# Generated by Django 4.2 on 2026-05-12 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_position_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='institution',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('teacher', 'Преподаватель')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('owner', 'code')},
        ),
        migrations.CreateModel(
            name='SeedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_hash', models.CharField(max_length=255, verbose_name='Хэш фразы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seed_phrase', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сид-фраза',
                'verbose_name_plural': 'Сид-фразы',
            },
        ),
    ]
