# Generated by Django 4.2 on 2026-05-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditlog_institution_institution_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_institutions',
            field=models.ManyToManyField(blank=True, related_name='allowed_users', to='core.institution', verbose_name='Доступные организации'),
        ),
    ]
