# Generated by Django 4.2 on 2026-05-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_allowed_institutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='notes',
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='institution',
            name='founded_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AddField(
            model_name='institution',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в систему'),
        ),
    ]
