# Generated by Django 4.2 on 2026-05-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_institution_photo_description_founded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Полное название'),
        ),
    ]
