# Generated by Django 4.2 on 2026-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_institution_code_alter_institution_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('login', models.CharField(blank=True, default='', max_length=150, verbose_name='Логин')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('purpose', models.CharField(choices=[('register', 'Регистрация'), ('recover', 'Восстановление пароля'), ('delete_org', 'Удаление организации')], max_length=20, verbose_name='Цель')),
                ('payload', models.TextField(blank=True, default='', verbose_name='Данные (JSON)')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email-код',
                'verbose_name_plural': 'Email-коды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.DeleteModel(
            name='SeedPhrase',
        ),
    ]
