# Generated by Django 4.2 on 2026-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emailcode_user_email_delete_seedphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Неверных попыток'),
        ),
    ]
