# Generated by Django 4.2 on 2026-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Отмечено'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Отмечено'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Отмечено'),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Отмечено'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Отмечено'),
        ),
    ]
