# Generated by Django 4.2 on 2026-05-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_employee_is_flagged_faculty_is_flagged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.IntegerField(verbose_name='ID объекта')),
                ('question', models.TextField(max_length=2000, verbose_name='Вопрос')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_notes', to='core.institution', verbose_name='Учебное заведение')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл')),
            ],
            options={
                'verbose_name': 'Вопрос по записи',
                'verbose_name_plural': 'Вопросы по записям',
                'ordering': ['-created_at'],
            },
        ),
    ]
