# Generated by Django 4.2 on 2026-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_student_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('secretary', 'Секретарь'), ('teacher', 'Преподаватель')], default='teacher', max_length=20, verbose_name='Тип роли'),
        ),
        migrations.AlterField(
            model_name='deleterequest',
            name='object_type',
            field=models.CharField(choices=[('Faculty', 'Факультет'), ('Group', 'Группа'), ('Position', 'Должность'), ('Student', 'Студент'), ('Employee', 'Сотрудник'), ('Parent', 'Опекун')], max_length=50, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('secretary', 'Секретарь'), ('teacher', 'Преподаватель')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('institution', 'name')},
        ),
    ]
