# Generated by Django 4.2 on 2026-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_position_role_type_alter_deleterequest_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('secretary', 'Секретарь'), ('teacher', 'Преподаватель'), ('none', 'Без доступа')], default='teacher', max_length=20, verbose_name='Тип роли'),
        ),
    ]
