# Generated by Django 4.2 on 2026-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Регистрация'), ('recover', 'Восстановление пароля'), ('delete_org', 'Удаление организации'), ('change_email', 'Смена email'), ('delete_account', 'Удаление аккаунта')], max_length=20, verbose_name='Цель'),
        ),
    ]
