# Generated by Django 4.2 on 2026-05-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_photo_alter_emailcode_purpose'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('institution', 'full_name'), ('institution', 'short_name')},
        ),
    ]
