# Generated by Django 4.2 on 2026-05-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_faculty_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='taught_subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.subject', verbose_name='Ведёт предметы'),
        ),
    ]
