# Generated by Django 4.2 on 2026-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_employee_taught_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('pending_review', 'На рассмотрении'), ('pending_enrollment', 'Ожидание зачисления'), ('enrolled', 'Активен'), ('pending_expulsion', 'На отчислении'), ('expelled', 'Отчислен')], default='pending_review', max_length=30, verbose_name='Статус'),
        ),
    ]
