# Generated by Django 4.2 on 2026-05-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_student_status_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
